### ISSUE TITLE
Help Movie Restorer

### ISSUE THREAD

**Issue by Nickyg001** [tomysshadow/Movie-Restorer-Xtra#4] opened 2023-12-12 19:48 UTC
I hope you can help me, my Director knowledge is zero...

I have video on DVD that were made with interfaces created with Director. The DVD contains both *.dxr, *.cxt project files, *.x32 [Xtra] files, and *.mov video files.

If I open the *.mov videos with any media player they can be listened to with the audio but the video cannot be seen.
To watch the videos I have to use the application created with director.
Since the videos were shot at a resolution of 1024x700px, today that I have a 4k monitor it is highly uncomfortable to watch these video.
There would be a way to be able to decrypt these videos so as to have a video that can be opened with any software, at least with that I can enlarge it to full screen since the application made with director does not allow zoom. Even if I have to reconvert all the videos.

**Comment by tomysshadow** [comment] 2023-12-12 22:05
This may be a silly question, but have you tried playing the video with
QuickTime Player itself? There is no difference in codec support between
Director's QuickTime Player and Apple's QuickTime Player: Director uses it
as a dependency. If there is no video there, then either the video is
stored separately (possible, but strange,) or (specifically if the DVD is
intended for Mac use only) the QuickTime Movie is split across multiple
resource forks and must be flattened.

**Comment by Nickyg001** [comment] 2023-12-12 23:48
The video files are in a separate folder, I tried to open them (on Windows) with multiple software and also with QuickTime but nothing works, only the audio is heard and the screen is black. Just a few Videos can be seen with any player, but out of 30 videos only 2 will be visible. the videos that are not visible are encrypted by a soresom codec it seems to me, I'm going from memory. But these same videos if I launch The application created with directories, they look good but only with that application. I would like to unlock those videos because I could manage the videos with a player like VLC so I could enlarge everything On the screen since with a 4k I struggle to follow 1024x700px videos.

**Comment by tomysshadow** [comment] 2023-12-12 23:54
Do you know which Director version it was created in? (unless it was
replaced it should say in the Version Info in Properties for the executable
itself)

**Comment by tomysshadow** [comment] 2023-12-13 00:03
also - does the Director app still work when copied off the DVD, or does it
have a no-CD check

**Comment by Nickyg001** [comment] 2023-12-13 00:08
If you leave me an email privately, I can send you the entire DVD tomorrow. It works even if copied to the hard disk. I don't know the version but they were definitely created in 2008.

Clearly I don't understand anything about Director and encrypted videos.

**Comment by tomysshadow** [comment] 2023-12-13 00:21
I was going to suggest you could use one of my Stretch Projectors. You can
find them here: https://mega.nz/folder/E053gI4C#aesGgLkf6V_YetWPNvEC-g

The idea is this: download the one for the correct Director version (try 10
to start, 11 if it doesn't work.) Next you'll need to copy
ProjectorStretch.exe into the folder where the original projector is so it
can find the Xtra's and Videos folders it'll expect to be there - since a
DVD is read only you'll need to copy the contents to disk in order to
insert ProjectorStretch there. Run it, then a file prompt will appear.
Select the main Director Movie (DIR/DXR/DCR) file. It'll attempt to run it
stretched to the full screen resolution.

The Stretch Projectors are at best experimental so this may not work - I
don't know how it will cope with resizing a QuickTime Movie - but if it
does it's the easiest way to solve your problem and won't require messing
about with weird codecs. Try it out and let me know.

**Comment by tomysshadow** [comment] 2023-12-13 00:23
*I'm also operating on the assumption the original projector is just a stub
that doesn't do much of anything. If that's not the case you might get a
dialog like "Script Error. Continue?" If so, it may be necessary to unpack
the movie out of that projector, which is also possible. But, I'll explain
how to do that if it's necessary.

**Comment by Nickyg001** [comment] 2023-12-13 08:39
Projector 11 worked by enlarging the window to full screen. It can be a palliative but not the definitive solution.
I'll send you the contents of the DVD so you can take a look at it, you certainly understand more than me who have 1% skills on the subject (that of double clicking on the *.exe 😁 )

Surely in the XTRA files there will be some extension that has the ability to read encrypted video files clearly, but my skills are equal to nothing on the subject.

**Comment by tomysshadow** [comment] 2023-12-13 09:05
In QuickTime, go to:
View > Preferences > QuickTime Preferences... > Advanced > Media Keys...

Click Add... and enter the following information.

Category: Sorenson Media
Key: ufogufo

Click OK to the dialogs to return to QuickTime, then go to File > Open File... and select your QuickTime Movie.

**Comment by Nickyg001** [comment] 2023-12-13 09:46
1. Works with ugogufo :)
2. Since I have others, can you teach me how to recover the key??
3. Except that now it only works with the Quicktime player, is there no way to make these videos accessible to other players too? also reconverting the videos if necessary.

**Comment by tomysshadow** [comment] 2023-12-13 09:50
I used the ProjectorRays decompiler. The handler to look for is qtRegisterAccessKey. It lives in Program.cxt, in this case. I work on the assumption that you legitimately own these materials and just want to view them at a larger resolution, so use that knowledge at your own risk.

Converting video codecs is well outside my area of expertise. I write Director Xtras, I'm not an ffmpeg maintainer

**Comment by Nickyg001** [comment] 2023-12-13 10:11
Then I'll try to use ProjectorRays decompiler and I'll update you if I succeed.
Yes, I have the DVDs of this material, my aim as I told you is to be able to view these videos on a large screen (since I have switched to a 4k monitor and the resolution of the videos is 1024x700 px and seeing them so small I am going blind, enlarged they are slightly blurry, but better than going blind.)


Where can I find "Projector Rays decompiler" and the guide to use it?

Could you kindly make me a video of all the steps to decompile and find the KEY?
I tried but then it gives me an error when opening the decompiled files and inside rerector it's a nightmare for me I don't understand much.

**Comment by Nickyg001** [comment] 2023-12-14 20:50
> In QuickTime, go to: View > Preferences > QuickTime Preferences... > Advanced > Media Keys...
> 
> Click Add... and enter the following information.
> 
> Category: Sorenson Media Key: ufogufo

Can this data be inserted into other software such as VLC, POTPLAYER etc or does it only work with QUICKTIME??

So as not to depend on QUICKTIME which I don't like on Windows?
Then can the data entered "Category and Keys" be saved in some file so as not to have to enter them again when I change PC or install the OS again?

**Comment by tomysshadow** [comment] 2023-12-15 02:12
Program.cxt is not a Director Movie, it is a Director Cast. ProjectorRays incorrectly gives it a .dir file extension when it decompiles it, but the correct file extension for the decompiled result is Program.cst (CST file extension is a Cast, CXT or CCT file extension is a Protected Cast.) While Director Movies may be opened directly with a simple double click, Director Casts are not intended to be directly used. This is because a Director Cast is a shared library. It is kind of like the distinction between an EXE and a DLL: you can directly open an EXE because it is standalone, but you're not intended to directly open a DLL. To open a Director Cast, you either need to open a Movie that uses the Cast or _link it_ to an existing movie.

Try this: in Director go to File > New to create a new movie, then go to Modify > Movie > Casts... > Link. Select your decompiled Program.cst here. Then, (if you don't see the Cast window) go to Window > Cast to open the Cast window, where your Program cast should now appear as a tab.

To search for the key, in the Cast window, right click on any member and select Cast Member Script... In the text editor that appears, hit Ctrl + F. Make sure the "All Casts" radio button is selected to search everything, then type in the handler name to search for "qtRegisterAccessKey" (without quotes.)

As far as I can tell, support for Media Keys in other media players is basically nonexistent, or at least I could not find anything on Google mentioning that it is possible. It is maybe possible that Sorenson's commercial encoder could convert it back though I couldn't find anything to definitively confirm that. Really the only mention I can find of this feature online at all is on [Dean's Director Tutorials](http://www.deansdirectortutorials.com/FAQ/video.htm) which just explains what it is and how to use it for QuickTime.

Perhaps if you'd like you can suggest it as a feature for those media player projects and maybe someone will take it on, though I suspect unless you want to try and figure it out yourself that it'd take quite some time for anyone to implement. I reported a bug in ffmpeg's handling of RealPlayer video to their bug tracker and it's been sitting as "reproducable" for over a year now

You could try the (practically ancient) video converter [EO Video.](https://web.archive.org/web/20031129191430/http://www.eo-video.com/) It doesn't mention support for Media Keys but it requires a QuickTime install in order to convert QuickTime video, implying to me that it directly uses the QuickTime engine as part of its conversion. I ran across this when trying to convert the aforementioned RealPlayer video that ffmpeg didn't want to convert, and it worked well for that. (No idea if it works well on Windows 10 - I was too cautious to run this outside of my Windows XP VM)

**Comment by tomysshadow** [comment] 2024-01-17 04:17
I'm going to assume the lack of a further response means you figured things out, and it was already quite off topic for Movie Restorer, so closing this.

**Closed as completed** 2024-01-17 04:19 UTC

**Comment by Nickyg001** [comment] 2024-11-08 09:31
> le seguenti informazioni.



> In QuickTime, vai su: Visualizza > Preferenze > Preferenze QuickTime... > Avanzate > Tasti multimediali...
> 
> Fare clic su Aggiungi... e immettere le seguenti informazioni.
> 
> Categoria: Sorenson Media Chiave: ufogufo
> 
> Fare clic su OK nelle finestre di dialogo per tornare a QuickTime, quindi andare su File > Apri file... e selezionare il filmato QuickTime.



Hi, just a small question that I can't find an answer to.
In QuickTime I enter all these values, Category and Key.
Having entered about ten entries, in case I had to format my computer to view the videos I would have to redo the operation from scratch to enter all the data. Is there a way to save this list, an external file where quicktime saves these values ​​so as to replace the file and already have the whole list compiled for easy and fast recovery?
Thank you very much.

**Comment by tomysshadow** [comment] 2024-11-08 10:11
The QuickTime Control Panel settings (including Media Keys) are stored on Windows in the file located at `%userprofile%\AppData\LocalLow\Apple Computer\QuickTime\QuickTime.qtp`
